GetEmployees:
    action: App\Infrastructure\Integrations\DummyRestApi\GetEmployees\Request\GetEmployeesAction
    method: GET
    path: /api/v1/employees



GetEmployee:
    action: App\Infrastructure\Integrations\DummyRestApi\GetEmployee\Request\GetEmployeeAction
    method: GET
    path: /api/v1/employee/{id}
