GetEmployees:
    action: App\Engine\Infrastructure\Integrations\DummyRestApi\GetEmployees\Request\GetEmployeesAction
    method: GET
    path: /api/v1/employees

GetEmployee:
    action: App\Engine\Infrastructure\Integrations\DummyRestApi\GetEmployee\Request\GetEmployeeAction
    method: GET
    path: /api/v1/employee/{id}

CreateEmployee:
    action: App\Engine\Infrastructure\Integrations\DummyRestApi\CreateEmployee\Request\CreateEmployeeAction
    method: POST
    path: /api/v1/create
    body: App\Engine\Infrastructure\Integrations\DummyRestApi\CreateEmployee\Request\CreateEmployeeBody

DeleteEmployee:
    action: App\Engine\Infrastructure\Integrations\DummyRestApi\DeleteEmployee\Request\DeleteEmployeeAction
    method: DELETE
    path: /api/v1/delete/{id}
