traditional_controllers:
    resource:
        path: ../src/Traditional/Controller/
        namespace: App\Traditional\Controller
    type: attribute

engine_controllers:
    resource:
        path: ../src/Engine/Controller/
        namespace: App\Engine\Controller
    type: attribute
