<?php

namespace ContainerGdGbb6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDummyRestApiIntegrationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Integrations\DummyRestApi\DummyRestApiIntegration' shared autowired service.
     *
     * @return \App\Infrastructure\Integrations\DummyRestApi\DummyRestApiIntegration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Registry/IntegrationName.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Integrations/DummyRestApi/DummyRestApiIntegration.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Registry/IntegrationRegistry.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/IntegrationEngine.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Port/ConfigPort.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Adapter/YamlConfigAdapter.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Contract/ClientInterface.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Http/SymfonyHttpClientAdapter.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Port/CachePort.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Cache/InMemoryCacheAdapter.php';

        $a = new \IntegrationEngine\Core\Registry\IntegrationRegistry();
        $a->register('dummy_rest_api', new \IntegrationEngine\Core\IntegrationEngine(new \IntegrationEngine\Infrastructure\Adapter\YamlConfigAdapter((\dirname(__DIR__, 4).'/src/Infrastructure/Integrations/DummyRestApi/DummyRestApi.yaml')), new \IntegrationEngine\Infrastructure\Http\SymfonyHttpClientAdapter(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), 'https://dummy.restapiexample.com', []), new \IntegrationEngine\Infrastructure\Cache\InMemoryCacheAdapter()));

        return $container->privates['App\\Infrastructure\\Integrations\\DummyRestApi\\DummyRestApiIntegration'] = new \App\Infrastructure\Integrations\DummyRestApi\DummyRestApiIntegration($a);
    }
}
