<?php

namespace ContainerGdGbb6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetEmployeesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetEmployees' shared autowired service.
     *
     * @return \App\Controller\GetEmployees
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GetEmployees.php';

        $container->services['App\\Controller\\GetEmployees'] = $instance = new \App\Controller\GetEmployees(($container->privates['App\\Infrastructure\\Integrations\\DummyRestApi\\DummyRestApiIntegration'] ?? $container->load('getDummyRestApiIntegrationService')), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\GetEmployees', $container));

        return $instance;
    }
}
