<?php

namespace ContainerGdGbb6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeIntegrationCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.IntegrationEngine\Bundle\Command\MakeIntegrationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.IntegrationEngine\\Bundle\\Command\\MakeIntegrationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:integration', [], 'Generates a new integration skeleton', false, #[\Closure(name: 'IntegrationEngine\\Bundle\\Command\\MakeIntegrationCommand')] fn (): \IntegrationEngine\Bundle\Command\MakeIntegrationCommand => ($container->privates['IntegrationEngine\\Bundle\\Command\\MakeIntegrationCommand'] ?? $container->load('getMakeIntegrationCommandService')));
    }
}
