<?php

namespace ContainerNHkQ2vR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetEmployeesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetEmployees' shared autowired service.
     *
     * @return \App\Controller\GetEmployees
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GetEmployees.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Registry/IntegrationName.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Integrations/DummyRestApi/DummyRestApiIntegration.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Registry/IntegrationRegistry.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/IntegrationEngine.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Port/ConfigPort.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Adapter/YamlConfigAdapter.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Contract/ClientInterface.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Http/SymfonyHttpClientAdapter.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Core/Port/CachePort.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Infrastructure/Cache/InMemoryCacheAdapter.php';

        $a = new \IntegrationEngine\Core\Registry\IntegrationRegistry();
        $a->register('dummy_rest_api', new \IntegrationEngine\Core\IntegrationEngine(new \IntegrationEngine\Infrastructure\Adapter\YamlConfigAdapter((\dirname(__DIR__, 4).'/src/Infrastructure/Integrations/DummyRestApi/DummyRestApi.yaml')), new \IntegrationEngine\Infrastructure\Http\SymfonyHttpClientAdapter(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), 'https://dummy.restapiexample.com', []), new \IntegrationEngine\Infrastructure\Cache\InMemoryCacheAdapter()));

        $container->services['App\\Controller\\GetEmployees'] = $instance = new \App\Controller\GetEmployees(new \App\Infrastructure\Integrations\DummyRestApi\DummyRestApiIntegration($a), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\GetEmployees', $container));

        return $instance;
    }
}
