<?php

namespace ContainerNHkQ2vR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeIntegrationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'IntegrationEngine\Bundle\Command\MakeIntegrationCommand' shared autowired service.
     *
     * @return \IntegrationEngine\Bundle\Command\MakeIntegrationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Bundle/Command/MakeIntegrationCommand.php';
        include_once \dirname(__DIR__, 5).'/integrationEngine/src/Bundle/Generator/IntegrationFileGenerator.php';

        $container->privates['IntegrationEngine\\Bundle\\Command\\MakeIntegrationCommand'] = $instance = new \IntegrationEngine\Bundle\Command\MakeIntegrationCommand(\dirname(__DIR__, 4), new \IntegrationEngine\Bundle\Generator\IntegrationFileGenerator());

        $instance->setName('make:integration');
        $instance->setDescription('Generates a new integration skeleton');

        return $instance;
    }
}
