<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGdGbb6Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGdGbb6Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGdGbb6Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGdGbb6Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGdGbb6Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'GdGbb6Z',
    'container.build_id' => '4d2e5ada',
    'container.build_time' => 1780575746,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGdGbb6Z');
